# Generated by Django 4.2.7 on 2026-01-04 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
        ('pdfs', '0001_initial'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pdfs.pdf'),
        ),
        migrations.AlterField(
            model_name='note',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='audios.audio'),
        ),
        migrations.AlterField(
            model_name='note',
            name='audio_timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
