# Generated by Django 4.2.7 on 2026-01-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_alter_folder_options_alter_folder_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('pdf', 'PDF')], default='audio', max_length=10),
        ),
    ]
